# Generated by Django 5.1.1 on 2024-09-25 06:03

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('attack-update', 'Attack Update'), ('cwe-update', 'Cwe Update'), ('capec-update', 'Capec Update'), ('cve-update', 'Cve Update'), ('cpe-update', 'Cpe Update'), ('arango-cti-processor', 'Cti Processor')], max_length=64)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('errors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), default=list, null=True, size=None)),
                ('run_datetime', models.DateTimeField(auto_now_add=True)),
                ('completion_time', models.DateTimeField(default=None, null=True)),
                ('parameters', models.JSONField()),
            ],
        ),
    ]
