# Generated by Django 5.2.4 on 2025-08-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_remove_vulmatch_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.CharField(max_length=24, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=256)),
                ('vendor', models.CharField(max_length=256)),
                ('softwares_count', models.IntegerField(default=1)),
            ],
        ),
    ]
