# Generated by Django 5.1.1 on 2024-11-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_job_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('cve-update', 'Cve Update'), ('cpe-update', 'Cpe Update'), ('arango-cti-processor', 'Cti Processor')], max_length=64),
        ),
    ]
