# Generated by Django 5.2.4 on 2025-08-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_productrevision_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrevision',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
