# Generated by Django 5.2.9 on 2025-12-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_productrevision_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPSSScore',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cve', models.CharField(max_length=20)),
                ('score', models.FloatField()),
                ('percentile', models.FloatField()),
                ('date', models.DateField()),
            ],
            options={
                'unique_together': {('cve', 'date')},
                'ordering': ['cve', '-date'],
            },
        ),
    ]
